from pathlib import Path
from typing import Any, Dict, List, Tuple
import numpy as np
import pandas as pd
from src.config import config


class MoodScorer:
    """Computes continuous Cowen mood dimensions from 1024-dim MERT embeddings.

    Loads fitted Ridge regression weights and biases generated by the
    MERT probe and performs linear projection.
    """

    def __init__(self, weights_path: Path | str | None = None):
        if weights_path is None:
            self.weights_path = (
                config["project_root"] / "datasets" / "cowen_mert_regression_weights.csv"
            )
        else:
            self.weights_path = Path(weights_path)

        if not self.weights_path.exists():
            raise FileNotFoundError(
                f"Mood weights not found at: {self.weights_path}. "
                "Run `uv run python -m src.scripts.cowen_regression mert` first."
            )

        print(f"Loading Cowen MoodScorer weights from: {self.weights_path}...")
        self.mood_names: List[str] = []
        self.weights: np.ndarray  # Shape: (1024, 24)
        self.biases: np.ndarray  # Shape: (24,)
        self._load_weights()

    def _load_weights(self) -> None:
        df = pd.read_csv(self.weights_path)
        self.mood_names = df["mood"].tolist()

        weight_cols = [f"w_mert_{i}" for i in range(1024)]
        missing_cols = [c for c in weight_cols if c not in df.columns]
        if missing_cols:
            raise ValueError(
                f"Corrupted weights file: missing {len(missing_cols)} weight columns."
            )

        # Transpose to shape (1024, N_MOODS) so we can compute: X @ W + b
        self.weights = df[weight_cols].values.T.astype(np.float32)
        self.biases = df["intercept"].values.astype(np.float32)
        print(f"MoodScorer ready: calibrated for {len(self.mood_names)} dimensions.")

    def score(
        self, embedding: np.ndarray | List[float]
    ) -> Tuple[Dict[str, float], List[float]]:
        """Projects a 1024-dimensional MERT embedding into mood space.

        Args:
            embedding: 1024-element vector (list or numpy array).

        Returns:
            A tuple of:
                1. moods_dict: {mood_name: score} (JSON-serializable)
                2. mood_vector: raw 24-dim continuous vector as list[float]
        """
        x = np.asarray(embedding, dtype=np.float32)
        if x.ndim != 1 or x.shape[0] != 1024:
            raise ValueError(f"Expected 1024-dim embedding vector, got shape {x.shape}")

        # Linear probe prediction: y = x @ W + b
        scores = np.dot(x, self.weights) + self.biases

        # Round and build dictionary for JSONB storage
        moods_dict: Dict[str, float] = {
            mood: round(float(val), 4) for mood, val in zip(self.mood_names, scores)
        }

        # Return both the dictionary and flat vector
        return moods_dict, [float(v) for v in scores]


_scorer_instance: MoodScorer | None = None


def get_mood_scorer() -> MoodScorer:
    global _scorer_instance
    if _scorer_instance is None:
        _scorer_instance = MoodScorer()
    return _scorer_instance
